# Define the root directories of the prediction and ground truth NIFTIs.
# The ground truth directory should be structured according to the Brain Imaging Data Structure (BIDS).
# The prediction directory should be structured according to in BIDS or the IF-Net-Output structure.
# Both directories must only include the segmentation masks and nothing else.
source_dir:
  gt: '/home/tomislav/datasets-ct-sized/dataset-CACTS/right kidney'
  pred: '/home/tomislav/outlier-detection/if-net/experiments/iVoxels_dist-0.5_0.5_sigmas-0.1_0.01_v128_mShapeNetPoints_perlin_treshold_085_087/evaluation_171_@256/generation/nifties/labels'

# Define which regions should be considered
# Accepted values: all, cervical, thoracic, lumbar
region: 'all'

# Define file to save results
results:
  file: 'scores.csv'
  overwrite_if_exists: True
